version: '3'

services:

  server:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION:-2017-latest-ubuntu}
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD:-upperio//s3cr37}
    ports:
      - '${BIND_HOST:-127.0.0.1}:${DB_PORT:-1433}:1433'

